import {
  index,
  jsonb,
  pgEnum,
  pgTable,
  real,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { documents } from "./documents";
import { anwendungsbereiche, kompetenzen } from "./lehrplan";
import { materialien } from "./materials";

/**
 * AI-tagging link between extracted material chunks and competencies.
 * Separate from user-driven `document_*_links`.
 */
export const materialKompetenzLinks = pgTable("material_kompetenz_links", {
  id: uuid("id").defaultRandom().primaryKey(),
  materialId: uuid("material_id")
    .notNull()
    .references(() => materialien.id, { onDelete: "cascade" }),
  kompetenzId: uuid("kompetenz_id")
    .notNull()
    .references(() => kompetenzen.id, { onDelete: "cascade" }),
  confidence: real("confidence").notNull(),
  rationale: text("rationale").notNull(),
  sourceChunkIds: jsonb("source_chunk_ids").$type<string[]>().notNull(),
  generatedBy: text("generated_by").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

/** Link Document ↔ Kompetenz, manually curated by teachers. */
export const documentKompetenzLinks = pgTable(
  "document_kompetenz_links",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    documentId: uuid("document_id")
      .notNull()
      .references(() => documents.id, { onDelete: "cascade" }),
    kompetenzId: uuid("kompetenz_id")
      .notNull()
      .references(() => kompetenzen.id, { onDelete: "cascade" }),
    note: text("note"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (t) => ({
    uniq: uniqueIndex("document_kompetenz_links_unique").on(
      t.documentId,
      t.kompetenzId,
    ),
  }),
);

/** Link Document ↔ Anwendungsbereich, manually curated by teachers. */
export const documentAnwendungsbereichLinks = pgTable(
  "document_anwendungsbereich_links",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    documentId: uuid("document_id")
      .notNull()
      .references(() => documents.id, { onDelete: "cascade" }),
    anwendungsbereichId: uuid("anwendungsbereich_id")
      .notNull()
      .references(() => anwendungsbereiche.id, { onDelete: "cascade" }),
    note: text("note"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (t) => ({
    uniq: uniqueIndex("document_anwendungsbereich_links_unique").on(
      t.documentId,
      t.anwendungsbereichId,
    ),
  }),
);

/**
 * AI-generated suggestions for links Document ↔ curriculum element.
 *
 * - `targetType` switches between Kompetenz and Anwendungsbereich; the
 *   matching foreign-key field is filled, the other one is `null`.
 * - `status` holds the review state of the suggestion (open / accepted /
 *   rejected). Accepted suggestions create a separate entry in
 *   `document_*_links`; the suggestion itself is kept for audit purposes.
 *   The string values stay German for now and will be migrated separately
 *   (see `TRANSLATION-TODO.md`).
 * - `confidence` is the model score (0..1).
 * - `rationale` is the German rationale text generated by the LLM.
 * - `model` is the ID string of the used LLM (for reproducibility).
 */
export const linkSuggestionStatusEnum = pgEnum("link_suggestion_status", [
  "open",
  "accepted",
  "rejected",
]);

export const linkSuggestionTargetTypeEnum = pgEnum(
  "link_suggestion_target_type",
  ["kompetenz", "anwendungsbereich"],
);

export const documentLinkSuggestions = pgTable(
  "document_link_suggestions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    documentId: uuid("document_id")
      .notNull()
      .references(() => documents.id, { onDelete: "cascade" }),
    targetType: linkSuggestionTargetTypeEnum("target_type").notNull(),
    kompetenzId: uuid("kompetenz_id").references(() => kompetenzen.id, {
      onDelete: "cascade",
    }),
    anwendungsbereichId: uuid("anwendungsbereich_id").references(
      () => anwendungsbereiche.id,
      {
        onDelete: "cascade",
      },
    ),
    confidence: real("confidence").notNull(),
    rationale: text("rationale").notNull(),
    model: text("model").notNull(),
    status: linkSuggestionStatusEnum("status").notNull().default("open"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    decidedAt: timestamp("decided_at", { withTimezone: true }),
  },
  (t) => ({
    docIdx: index("document_link_suggestions_document_idx").on(t.documentId),
    uniqKomp: uniqueIndex("document_link_suggestions_kompetenz_unique").on(
      t.documentId,
      t.kompetenzId,
    ),
    uniqAwb: uniqueIndex(
      "document_link_suggestions_anwendungsbereich_unique",
    ).on(t.documentId, t.anwendungsbereichId),
  }),
);

export type DocumentLinkSuggestion =
  typeof documentLinkSuggestions.$inferSelect;
export type NewDocumentLinkSuggestion =
  typeof documentLinkSuggestions.$inferInsert;
